###
GET http://localhost:8000/

###
GET http://localhost:8000/pets

###
GET http://localhost:8000/pets/0

###
GET http://localhost:8000/pets/1

###
GET http://localhost:8000/pets/2

###
GET http://localhost:8000/pets/-1

###
GET http://localhost:8000/something



###
GET http://localhost:3000/pets
Authorization: Basic YWRtaW46bWVvd21peA==

###
POST http://localhost:3000/pets
Authorization: Basic YWRtaW46bWVvd21peA==
Content-Type: application/json

{
    "age": 1000,
    "kind": "space whale",
    "name": "yoooooooo"
}

###
GET http://localhost:3000/aksjg
Authorization: Basic YWRtaW46bWVvd21peA==

###
PATCH http://localhost:3000/pets/2
Authorization: Basic YWRtaW46bWVvd21peA==
Content-Type: application/json

{
    "kind": "emu"
}

###
DELETE http://localhost:3000/pets/2
Authorization: Basic YWRtaW46bWVvd21peA==