###
GET http://localhost:8000/

###
GET http://localhost:8000/pets

###
GET http://localhost:8000/pets/0

###
GET http://localhost:8000/pets/1

###
GET http://localhost:8000/pets/2

###
GET http://localhost:8000/pets/-1

###
GET http://localhost:8000/something



###
GET http://localhost:3000/pets

###
POST http://localhost:3000/pets
Content-Type: application/json

{
    "age": 100,
    "kind": "emu",
    "name": "Bro"
}

###
GET http://localhost:3000/aksjg

###
PATCH http://localhost:3000/pets/2
Content-Type: application/json

{
    "kind": "emu"
}

###
DELETE http://localhost:3000/pets/2